FROM mcr.microsoft.com/devcontainers/miniconda:1-3

# Preinstall any light system deps if you need
# RUN apt-get update && apt-get install -y <optional-packages>

# Copy your environment.yml (but don't build yet)
COPY environment.yml /tmp/conda-tmp/environment.yml
