name: ondas2
channels:
    - defaults
    - conda-forge
dependencies:    
    - python=3.8
    - scipy=1.10.1
    - matplotlib
    - netCDF4=1.6.3
    - notebook=6.5.2
    - numpy=1.23.5
    - pandas=1.5.2
    - panel=1.2.1
    - progressbar
    - plotly=5.13.1
    - xarray=2022.11.0
    - gsw
    - sympy=1.12
    - UTide=0.3.0
    - shapely=2.0.1
    - seaborn=0.12.2
    - windrose=1.9.0
    - jupyterlab=3.5.3
    - folium
